name: vscode-binder
channels:
  - conda-forge
dependencies:
  - numpy
  - python-build
  - jupyter-server-proxy
  - code-server >=3.2
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - plotly
  - bs4
  - rise
